### ISSUE TITLE
Startpages WIP

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe#148]
BACK
- [x] interdire l'ajout manuel de startpage appartenant à une autre WebEntité (cf #109) 
- [x] permettre de combiner les heuristiques
- [x] modifier heurisitique "pages" pour prendre les N pages les plus citées
- [x] définir l'heuristique par défaut en config globale/locale
- [x] fournir en API le résultat d'une heuristique pour une webentité, unicisé et catégorisé par type (ordre: startpages/pages/prefixes) pour permettre au front de lookupper et setter en manuel
- [x] au lancement d'un crawl, on utilise les startpages de la WE s'il y en a si, sinon on applique l'heuristique
- [x] dès qu'une startpage auto a été crawlée, si httpstatus ok elle est ajoutée aux startpages de la webentité et un tag core-startpage-auto est ajouté
- [x] quand on supprime une startpage, on vérifie et supprime l'éventuel tag auto associé 
- [x] fournir en API la liste des startpages d'une webentité dissociées manuelles/auto
- [x] fournir en API la liste des crawls associés à une webentité
- [x] ... une fois les homepage gérées ajouter "homepage" aux heuristiques possibles

FRONT
- [x] dans CheckStartpage tant qu'une webentité n'est pas dépliée on ne fait pas de lookup ni aucune opération sur les startpages (renommer page en PrepareCrawls du coup?).
- [x] on n'essaie plus de générer de variantes https/www depuis le front
- [x] quand on clique pour déplier une webentité qui a des startpages on lance les lookups dessus
- [x] quand on clique pour déplier une webentité qui n'a pas de startpage, on demande au core l'heuristique par défaut (et propose optionnellement d'autres heuristiques?) et lance les lookups sur les startpages résultantes
- [x] les webentités à crawler issues de ImportUrls génèrent toujours des webentités dépliées dans CheckStartPages (=> lookup, mais sans les variantes?)
- [x] les webentités à crawler issues de LIST ou PROSPECT sont toujours repliées par défaut dans CheckStartPages
- [x] au lookup, si une startpage redirige vers une page dans la même webentité la résoudre automatiquement (ou ne pas afficher d'erreur vu que le crawler se débrouillera) cf #184
- [x] à l'ajout/suppression manuel de startpage, ne recharger le lookup que pour celle-ci et non pour toutes les autres
- [x] à l'ajout de startpage manuel, demander au core si elle appartient bien à la webentité pour proposer le modal de merge webentites ou ajout de prefixe sinon (cf #109)
- [x] dans la page WebEntity, afficher la liste des startpages, dissociées manuelles/auto
- [x] ~~dans la page WebEntity, afficher la liste des crawljobs associés~~
- [x] ~~... une fois les startpages simplifiées besoin de page de monitoring de la qualité des crawls~~
